# Workflow for Maui-annotation proejcts{#maui}

## Read this in case

- you have run a succesfull Maui project
- exported all required container (see \@ref(container))
- you have a copy of sequence list and experimental conditions
- you know the extraction procedure

The following article describes briefly how to use MTXQCvX2 in case you used Maui for the annotation of your metabolomics project. It does not matter if you have performed an experiment 
including stable isotopes or if you just aim for the quantification of a few intermediates. 

## Quick view

1. Setup a new R-project and copy MTXQC-files
2. Knit with parameter: `MTXQC_init.Rmd`
3. Copy input files and rename ManualQuantTable.tsv (e18205cz.tsv) 
4. Create annotation.csv and sample_extracts.csv files
5. Define the internal extraction standard^[see below InternalStandard]
6. Knit with parameter: `MTXQC_ExperimentalSetup.Rmd` 
7. Knit with parameter: `MTXQC_part1.Rmd` 
8. Knit with parameter: `MTXQC_part2.Rmd` 
9. If required, proceed with `MTXQC_part3.Rmd` - ManualValidation

## Input files 

Input files for the MTXQCvX are generated by using the export functions implemented in Maui. 
Specific containers have to be exported and moved into their corresponding `input` folder.
Follow the instructions which Maui container have to be exported described at \@ref(mauiexport).

Certain circumstances might require the combination of _multiple MAUI-projects_ into one MTXQC-project. This might be the case when you run the same samples in split and splitless mode on the machine or your experimental setup has been measured in multiple batches in order to avoid derivatisation effects.

It is recommended to combine the input files derived from a different number of Maui projects beforehand. In that way you have to work with a single file `CalculationFileData.csv` containing all experimental data points

The herein described process provides a quick way how to combine the exported files from different Maui projects. The script `combine-sets.R` saves all combined files into the correct `input` folder. Just update the folder and subfolder names. All the rest has been taken care of for you.

1. Create in the MTXQC-project folder (e.g., `psirm_glucose/`) a new folder, e.g., `raw-data`
2. Create subfolder for each MAUI-run in `psirm_glucose/raw_data`
3. Copy the required input files into each subfolder
4. Update the parameter of template file `combine-sets.R` file^[inst/template_files/...]
5. Execute the script and check the generated files
6. Merged files have been generated and copied into the corresponding folder: `psirm_glucose/input-folder/gc/...` or `psirm_glucose/input-folder/inc/...`
7. Copy the renamed tsv-files separately into input/quant/...

## Annotation-file

The annotation file relate file names with experimental conditions or specify quantification standards in your batch. Two columns - **File and Type** - are obligatory and have to be present in the annotation file. In the case of absence MTXQCvX_part1 stops processing and shows an error message.

A quick way to generate an annotation file is described below:

1. Copy the first row / header of `quantMassAreaMatrix.csv` file
2. Paste & transpose the content into a new Excel-File into column A
3. Change Metabolite to File
4. Remove the entry QuantMasses at the very end of the column A
5. Add the column Type and specify each file either as sample or addQ1_dilution^[see for further details additionalQuant]
6. Add more columns specifying your experimental conditions, e.g., Cellline and Treatment ...^[optimal: two-three parameter, max: four parameter. Consider possible combinations, e.g., HCT116-control, HCT116-BPTES]
7. Save the content as `csv-file` in the `psirm_glucose/input/...`

## Sample_extracts-file

The `sample_extracts.csv` file helps to determine correct absolute quantities in the manner of pmol/1e+6 cells or pmol/mg tissue in the `CalculationFileData.csv`.

This file requires two obligatory columns and have to be included: **Extract_vol** and **Unit**^[Define: count, mg or ul]. Please specify for each experimental condition the amount of extracted cells (count), tissue (mg) or volume of blood/plasme (ul) in the unit shown in the brackets.  
The names of the columns of the experimental conditions have to match up with the annotation file. Save the file in the folder `psirm_glucose/input/...`. 

If the defined experimental conditions do not match up with the annotation MTXQCvX2_part1.Rmd exit data processing.

A template file can be modified and reused: `inst/template_files/...` 

## Internal Standard

MTXQCvX2 allows the specification of project-specific internal extraction standards. The only thing you need to do is to define the corresponding compounds as an internal standard in the `conversion_metabolite.csv` file. To do so add `InternalStandard` in last column `Standard`.

For an classical pSIRM experiment in the Kempa lab we are using cinnamic acid. The evaluation of this compound has been integrated into maui and peak areas are exported from a distinct container called `cinAcid`. The exported file has to be renamed to `InternalStandard.csv` and moved to `psirm_glucose/input/gc/...`.

If you have used a different compound as an internal extraction standard you might need to extract the peak areas of this compound from the file `quantPeakAreasMatrix.csv` file and save it in the folder `psirm_glucose/input/gc/InternalStandard.csv`, respectively. Prerequisite - you annotated the compound in Maui.

The report of `MTXQCvX2_part1.Rmd` includes the detected internal standard for each project.


