# Data processing - MAUI{#proc:maui}

## Processing In ChromaToF

Create a new folder in ChromaToF Pegasus Acquired Samples and import your files.
The processing of files for Maui-assisted annotation is a two step process. 
Therefore two data processing methods have to be set up and applied to all files. 

### Resampling

Resampling is commonly applied and results into a data transformation enabling an improved detection of low abundant peaks and a reduction of noise. (Maybe include an example?)

The processing methods requires to tick `Export of ...`. Subsequently, you are asked to define an output folder and the following paramter:

- Reduction rate: 4
- Beginning to end of the file
- `.peg`-files

### Combo-export (`.cdf` \& `.csv`)

Re-import the generated `.peg`-files into a subfolder and apply the following data processing method.

Activate the box `asddasd` and define for both file types the following parameter.

`.cdf`-file:

- export directory
- 


`.csv`-file:

- export directory
- 



                      

## Maui notes




## Maui exports{#mauiexport}

With initiation of a project folder via `MTXQCvX2_init.Rmd` you created an `input`-folder containing three subfolders: `gc`, `inc`, `quant`. In the following all files that should be exported and copied into these folders are described in detail.


### `input/gc/...` 

Four input files are exported in order to assess the quality of the GC-MS performance of the run. The menue `Diagnostics` is selectable via right click on your Maui project name. Only the cinnamic acid peak areas are exported via the function `Export Quantification` with right click on the actual container.

Exported Files: 

- `Alcane_intensities.csv` - Diagnostics/Export Alcane intensities
- `InternalStandard.csv` - cinAcid container, Export quantification, rename!
- `MassSum-73.csv` - Diagnostics/QC Mass Sum Export;  enter: 73 for m/z 73
- `PeakDensities-Chroma.csv` - Diagnostics/ExportPeakDensities

### `input/quant/...`

Only one container has to be exported and contains the peak areas of each metabolite and
measurement. Keep in mind that you should have uploaded `pTop5 mass list` for the correct determination of peak areas in case of labeling with stable isotopes.

A further note - Maui performs absolute quantification and stores values in the `samplePeakGroups-QMQ` container. These quantities are determined by polynominal regression, and not linear regression. 

The file `ManualQuantTable.tsv` is automatically generated by Maui during processing the absolute quantification.

Exported Files:

- `ManualQuantTable.tsv` - location: `Maui-project/export/QM-AbsoluteQuantification/...`^[Don´t forget to rename it - e.g., e17123cz] 
- `quantMassAreasMatrix.csv` - Quantification export of the container `samplesPeakGroups`

### `input/inc/...`

This exports are only required in case of an experiment including the application of stable isotopes. It´s this the case you should have performed two things:

1. Used the optional upload of `pTop5 mass list`
2. Go through the pSIRM workflow in Maui


Exported Files:

- `DataMatrix.csv` - Export \% Label of container `pSIRM-samplesPeakGroups`
- `pSIRM_SpectraData.csv` - pSIRM Spectra Export of container `pSIRM-samplesPeakGroups`^[Requires the selection of Natural_MIDs.txt]

