# Protocols

## Sample extraction
### Cell extracts

Materials:

- cell culture dishes (10 cm)
- 50 \% MeOH plus 2 ug/ul cinnamic acid, ice-cold
- chloroform
- 15 ml falcon tubes
- cell lifter

Procedure:

- prepare cell culture dishes accordingly to your experimental conditions
- discard media / buffer
- add immediately 5 ml MeOH
- detach cells using cell lifter
- collect and transfer cell extract into 15 ml falcon
- add 1 ml chloroform
- incube for 30 - 60 min at cold temperature on rotary or thermo shaker
- centrifuge at max speed for 10 min
- collect polar and lipid phases
- dry under vacuum

In order to generate technical backups:

- resuspend dried extracts in 600 ul 20 \% MeOH
- shake at cold temperature on thermo shaker for 30 min
- split volumes into equal parts in fresh eppendorf tubes
- dry under vacuum

Suggested cell density: $2-3e+6$ cells / extract.

### Tissue samples

### Blood samples


## Sample derivatisation




## GC-MS measurement




## Data processing


### Processing for Maui annotation

#### Resampling

#### Combo-export

#### Maui quantification masses

#### MAUI pSIRM

#### Maui exports{#mauiexport}

1. Input-Folder: gc 

- Alcane_intensities.csv (Diagnostics/Export Alcane intensities)
- InternalStandard.csv ^[see more details below]
- MassSum-73.csv (Diagnostics/QC Mass Sum Export for mass 73)
- PeakDensities-Chroma.csv (Diagnostics/ExportPeakDensities)

2. Input-Folder: quant

- ManualQuantTable.tsv - **rename it** - e.g., e18125cz.tsv ^[Location: Maui-project/export/QM-AbsoluteQuantification/...] ^[C://Users/User-name/MauiProjects/...]
- quantMassAreasMatrix.csv (Quantification export of samplesPeakGroups)

3. Input-Folder: inc

- DataMatrix.csv (Export \% Label of pSIRM-samplesPeakGroups)
- pSIRM_SpectraData.csv (pSIRM Spectra Export)^[Requires the selection of Natural_MIDs.txt]


### Processing for Metmax data extraction

#### Resampling

#### 1D-basic

#### Reference search

#### Export for Metmax

#### Data extraction

