# Protocols - Sample extraction

## Cell extracts

Materials:

- cell culture dishes (10 cm), max. confluency 75\%
- washing buffer (Hepes, NaCl, ph 7.4)
- 50\% MeOH, ice-cold
- 2 mg/ml cinnamic acid
- chloroform
- 15 ml falcon tubes
- cell lifter

Procedure:

- prepare cell culture dishes accordingly to your experimental conditions
- discard cell culture media
- add quickly 5 ml of washing buffer, discard it
- add very immediately 5 ml ice-cold 50\% MeOH suppl. 2 ug/ul cinnamic acid
- detach cells using cell lifter
- collect and transfer cell extract into 15 ml falcon
- store falcons until further processing on ice
- add 1 ml chloroform
- incube for 60 min at cold temperatures (4 C) on rotary or thermo shaker
- centrifuge at max speed for 10 min, cold temperatures
- collect polar and lipid phases into fresh falcons / tubes
- dry under vacuum

In order to generate technical backups:

- resuspend dried extracts in 600 ul 20\% MeOH
- shake at cold temperature on thermo shaker for 30 min
- split volumes into equal parts in fresh eppendorf tubes
- dry under vacuum

Suggested cell density: $2-3e+6$ cells / extract.

## Tissue samples

Materials:

- Methanol:Chloroform:Water (MCW) in ratio 5:2:1
- 2 mg/mg cinnamic acid in MeOH
- ddH20
- eppendorf tubes
- tissue lyzer / pulverizer

Procedure:

- snap-freeze tissue samples
- pulverize samples
- aliquote 50 mg of tissue powder
- add 1.5 ml of MCW (suppl. with cinnamic acid final conc. 2 ug/ul)
- shake for 60 min on rotary shaker at cold temperature (4 C)
- add 0.5 ml ddH20 for phase separation
- centrifuge maximum speed, 10 min, cold temperatures
- collect polar and lipid phases in fresh vessels
- dry under vacuum


## Blood samples

Material:

- Methanol:Chloroform:Water (MCW) in ratio 5:2:1
- 2 mg/mg cinnamic acid in MeOH
- ddH20
- eppendorf tubes 

Procedure:

-	give 20 ul blood / sera directly into 1 ml MCW to avoid lumps
- in case of lumps sonicate samples
- shake samples at 4 C for 800 rpm for 60 min
- add 500 ul ddH20 and vortex shortly
- spin down at 4 C at max speed for 10 min
- aliquote polar phase into 2-3 times 500 ul in 1.5 ml tubes
- aliquote lipid phase 2 times in 100 ul lower in 1.5 ml eppi
- dry in SpeedVac (35 C)

